# Generated by Django 4.2.7 on 2026-01-12 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stoke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_hora_cierre', models.DateTimeField(auto_now_add=True)),
                ('dinero_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Dinero inicial en caja', max_digits=10)),
                ('dinero_final', models.DecimalField(decimal_places=2, default=0, help_text='Dinero final en caja', max_digits=10)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tarjeta_debito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tarjeta_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_mercado_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_ventas', models.IntegerField(default=0)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia entre dinero final esperado y real', max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha_hora_cierre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'ordering': ['venta', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Producto activo para ventas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras del producto', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(blank=True, help_text='Tamaño o presentación (ej: 500ml, 1L, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta Débito'), ('tarjeta_credito', 'Tarjeta Crédito'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto recibido del cliente (solo para efectivo)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='recargo_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recargo aplicado por pago con tarjeta', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vuelto a entregar (solo para efectivo)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras'], name='stoke_produ_codigo__d7bfca_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='stoke_produ_nombre_463431_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='stoke_venta_fecha_1614f8_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['metodo_pago'], name='stoke_venta_metodo__f328db_idx'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stoke.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stoke.venta'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cierrecaja',
            unique_together={('fecha', 'usuario')},
        ),
    ]
